### ISSUE TITLE
Contrary to the readme, Cursive supports :local/root component deps

### ISSUE THREAD

**Issue by imrekoszo** [polyfy/polylith#127]
In the readme there is the following section (and later on, there are constraints set by this section):

```
An alternative way of adding the component is by specifying it as an :extra-deps (the development/src directory still has to be specified as a path):

 :aliases  {:dev {:extra-paths ["development/src"]
                  :extra-deps {poly/user {:local/root "components/user"}}
  ...
            :test {:extra-paths ["components/user/test"]}
If you use Cursive as an IDE, this will not work correctly, and the problem is that Cursive doesn't treat components/user/src as a source directory in the IDE (it will not be marked as green). This is also why we use the first form in this example.
```

Cursive does support this, however. Here's how to make that work:

1. add the local/root dep to the root deps.edn
2. `File > New... > Module from Existing Sources...` or use the `Import Module from Existing Sources...` action
3. browse to the workspace root folder, Open and navigate through the wizard:

![Screenshot 2021-09-07 at 15 13 34](https://user-images.githubusercontent.com/1116295/132351488-28d2a4a3-0329-4038-ba99-41176700ad0a.png) 
![Screenshot 2021-09-07 at 15 13 51](https://user-images.githubusercontent.com/1116295/132351574-2643c6d6-bfd9-487d-bc65-3da226dd9a5a.png)
![Screenshot 2021-09-07 at 15 13 59](https://user-images.githubusercontent.com/1116295/132351584-bd07b559-11e3-4812-baa0-bc2953ead893.png)
![Screenshot 2021-09-07 at 15 14 04](https://user-images.githubusercontent.com/1116295/132351600-f8b127be-acf0-4551-afb4-a75bfa86876b.png)

Your component src/test folders should now be properly marked:
![Screenshot 2021-09-07 at 15 14 27](https://user-images.githubusercontent.com/1116295/132351621-7f18173c-4c21-4938-a834-3bffa5c82030.png)

**Comment by tengstrand** [comment]
This is great! 
As soon as me and @furkan3ayraktar have verified that this works (which I don't doubt) I will update the documentation!
Thanks again @imrekoszo!

**Comment by furkan3ayraktar** [comment]
I've tested it in my project with Cursive and I still cannot make the tests work with this approach. Even though it seems like Cursive detects the test directories as test resources, they are not included in the classpath when the REPL is started. I guess this is due to the fact that the test resources and dependencies are not included when the components and bases are included as `:local/root`. 

One workaround is adding the components and bases as `:local/root` and including their test directories and test dependencies directly in the `:test` alias of the root `deps.edn` file. This way, they could be reachable from REPL. However, I find it weird to mix two different ways to setup root `deps.edn` so I would still stick with the current suggestion for Cursive. 

Maybe some day Cursive will support Polylith workspace structure!

**Comment by imrekoszo** [comment]
> One workaround is adding the components and bases as :local/root and including their test directories and test dependencies directly in the :test alias of the root deps.edn file. This way, they could be reachable from REPL. However, I find it weird to mix two different ways to setup root deps.edn so I would still stick with the current suggestion for Cursive.

But this^ is exactly what the readme suggests works with emacs etc but _not_ cursive, when indeed it does.

Readme says this is what works with Cursive:

```clojure
 :aliases  {:dev {:extra-paths ["development/src"
                                "components/user/src"
                                "components/user/resources"]
  ...
            :test {:extra-paths ["components/user/test"]}
```

Readme says this is what doesn't work with Cursive:

```clojure
 :aliases  {:dev {:extra-paths ["development/src"]
                  :extra-deps {poly/user {:local/root "components/user"}}
  ...
            :test {:extra-paths ["components/user/test"]}
```

Both of these have the test folder as an extra path, and that's because of how tools.deps constructs the classpath, not because of the editor.

**Comment by furkan3ayraktar** [comment]
I have tried it again with using :local/root for :dev alias and :extra-paths for the :test alias. I’ve added each component and base as modules. I can start a REPL from within Cursive and it seems like it has the correct classpath. However, Cursive does not resolve references to namespaces from other components.

Based on the discussion with @imrekoszo and others on Clojurians Slack, it appears that the module approach suggested in this issue does not work since this requires each component to depend on other components in their `deps.edn` files. Since that is not possible with Polylith, we can still say `:local/root` version is not supported with Cursive.

**Comment by imrekoszo** [comment]
Thanks for clearing that up @furkan3ayraktar! I only dipped my toe into polylith and wasn't aware that bricks shouldn't have direct deps on each other (if they do, then Cursive's module approach works). Perhaps the readme could be clearer about this caveat.

Apologies for making all the noise :)

**Comment by furkan3ayraktar** [comment]
Yeah, no worries! Glad to help out and have a discussion!
