### ISSUE TITLE
Polylith should manage its own brew tap

### ISSUE THREAD

**Issue by seancorfield** [polyfy/polylith#131]
**Is your feature request related to a problem? Please describe.**
The core Brew team has very strong opinions on how `brew` formulae should work and a key part of that is that `brew` always installs all the dependencies a package says it needs and always installs the latest version. This means that `brew install poly` will force an OpenJDK 16 install on all users. The Clojure CLI had this happen too, with the core Brew team modifying the `clojure` formula to bring in OpenJDK 16. See https://github.com/Homebrew/homebrew-core/issues/50536 for the background and discussion.

**Describe the solution you'd like**
In the same way that the Clojure team now manages its own `brew` tap at `clojure/tools/clojure`, I think the Polylith team should set up and manage their own tap so that they can control exactly which versions of dependencies get installed -- and indeed if the user has an appropriate `openjdk` already installed, it shouldn't force install a newer version.

**Describe alternatives you've considered**
There's no real alternative: either you live with the Brew rules and have people complain about `brew install poly` changing their installed version of Java, or you run your own tap.

**Additional context**
I don't know how the Clojure team got their tap registered -- you'd have to ask @puredanger about that.

**Comment by puredanger** [comment]
There is no registration, you just follow the naming convention. https://docs.brew.sh/Taps

**Comment by furkan3ayraktar** [comment]
Polylith has its own brew tap, just like Clojure: [https://github.com/polyfy/homebrew-polylith/tree/master/Formula](polyfy/homebrew-polylith)

@puredanger I checked the Clojure Formula now, it does not state that it depends on Java. Polylith Formula states specifically it depends on Java. 

If we don't put Java dependency in brew Formula, what happens if someone installs Polylith (or Clojure) without having installed Java beforehand?

**Comment by puredanger** [comment]
Then it won't work.

**Comment by puredanger** [comment]
Your choices are: depend on Java and get the newest release if you don't have it. OR don't depend on Java, check for that, and tell the user what to do if Java isn't installed. brew used to have support for "ensure Java exists, but leave it alone if it's at least version whatever and/or install version whatever".

**Comment by furkan3ayraktar** [comment]
Got it! I guess it's better to let brew install Polylith without Java since installing it does not require Java. 

Then, in the bash script that actually runs Polylith from the `jar` file, we can check if Java exists. If not, we can show an error and maybe a hint for the user to install Java.

**Comment by furkan3ayraktar** [comment]
I have updated the `brew` formula so that it does not depend on Java anymore. You can check out the commit [here](https://github.com/polyfy/homebrew-polylith/commit/3578c813bc776dae10cdbe9a0f61754b2ae2ab71).

If you uninstall poly with `brew uninstall poly` and install it again `brew install polyfy/polylith/poly` you'll get the one without the java dependency. The bash script that runs the `poly` first checks if there is a `java` executable in the path current. If it exists, it uses it, otherwise it checks if `JAVA_HOME` is set and tries to find `java` executable in it. Otherwise, it will print out an error message that it couldn't find `java` and exit with code 1.

You can have a look at the full script that runs `poly` [here](https://github.com/polyfy/polylith/blob/master/components/deployer/src/polylith/clj/core/deployer/core.clj#L74).

**Comment by seancorfield** [comment]
I think we're OK to close this out now?
