### ISSUE TITLE
Use tools.build

### ISSUE THREAD

**Issue by tengstrand** [polyfy/polylith#134]
**Is your feature request related to a problem? Please describe.**
The Polylith codebase itself and the main example use [depstar](https://github.com/seancorfield/depstar) today, which has reached the end of its life and recommend people to use [tools.build](https://github.com/clojure/tools.build). 

**Describe the solution you'd like**
Convert the examples and the `deployer` component to use `tools.build`.

Take a look at [build-clj](https://github.com/seancorfield/build-clj) as a way to reduce boilerplate code in `build.clj` files.

**Comment by seancorfield** [comment]
I'm taking a week off work and I expect to spend several days working on OSS projects so I'm probably going to start submitting PRs around this issue.

I see two main areas:
* the documentation (readme) and the accompanying `doc-examples` projects
* Polylith's own `projects` and the `build*.sh` scripts

I'm not clear on the `scripts/sections` stuff which also references `depstar` at the moment.

There's also the `toolsdeps*_project_deployable_config_test` files that still reference `uberdeps`?

**Comment by tengstrand** [comment]
Okay, cool. 

I plan to publish my work (push it to a separate branch) on issue #106 (shell command) next weekend and I will also move all the poly documentation to gitbook at the same time. This means that changes to the documentation will soon be maintained from gitbook and not from the polylith repository.

The `doc-example` project is generated from the `scripts/create-example.sh` script and should be left untouched (it is produced by the commands from the example and the final result is then copied to the `examples/doc-example` directory).

The uberdeps reference in `polylith.clj.core.validator.datashape` can be left as it is. That data structure is only used to test the code that validates a `deps.edn` data structure (and specifying an :uberjar alias should be allowed).

The `build.sh` script needs to be converted + the code in the `deployer` component.

**Comment by seancorfield** [comment]
Thanks. That helps. I'll focus on the actual Polylith build/deploy stuff first and may get an initial round of documentation work in this week as well, _before_ you convert stuff over (if it doesn't get merged, I can always redo it against the gitbook setup I guess?).

Knowing more about those other bits is helpful. Maybe at some point, we can get a "contributors' guide" together that wraps up all this information in one place -- so it's not just in your head (and @furkan3ayraktar's head).

I'm adding in your notes from Slack as well so at least this thread contains "everything":

Before I push something, I perform these steps:

* Execute the `./build.sh` script to see that I can build a working jar (that I also use locally).
* Execute `poly test :all` which will run all the tests from the `poly` project.
* Execute the `create-example.sh` script. What it does is described in the script itself, but in short it’s used to produce files that make my life easier and to verify that the compiled `poly` command works as expected. This step sometimes involves manual work, e.g. when the output from any command has changed.

To deploy we perform these steps:

* Update the code and documentation to use the latest release in a few places.
* Update the `sha` in the `Add other Polylith artifacts as a dependency` section to use the latest sha.
* Once these changes are made to the master branch, we create a tag and push it to the master branch, e.g. `v0.2.13-alpha`.
* Once the CircleCI finishes the deployment, it will be deployed to Clojars and GitHub automatically.
* Finally we update the version of the homebrew-polylith packages and push those changes.

I think that was all. As you can see, there are a few manual steps involved today.

**Comment by tengstrand** [comment]
I've created the gitbook documentation already and I will get it proofread later today (Monday). I can probably publish the documentation earlier, maybe on Tuesday. Then you should be able to contribute directly to the documentation (in a branch) in gitbook.

Setting up a contributors guide sounds like a good idea to me.

**Comment by seancorfield** [comment]
That's great news! I think that will be a huge improvement to the onboarding of new Polylith users!

**Comment by seancorfield** [comment]
I've spent a couple of hours trying to figure this out and I'm pretty confused now.

There's a `build-api.sh` which tries to build an **uberjar** of the `api` project but there's no `:uberjar` alias so that won't work. Is this just an orphan script? Same Q for `build-core-api.sh` which tries to build an uberjar of the `core` project when there's no `:uberjar` alias there either.

The `deployer` project has a lot of stuff essentially hard-coded into it that should be in `build.clj` -- and the `partial_pom.xml` stuff hardcodes dependencies that should be derived from `deps.edn` instead. It only seems to exist so that `VERSION` can be substituted -- but both `depstar` and `tools.build` could do that for you anyway. I suspect the `deployer` is very much legacy code and could be completely replaced by `tools.build` since that has functionality to copy files and folders and make text substitutions.

The `build-uberjar.sh` script seems to be the master version that is copied into other places as part of building the doc examples stuff which means if I change it to run `clojure -T:build uber ...` -- which is the `tools.build` way -- then all of the doc sections end up needing to use `tools.build` as well and they all need a `build.clj` script added to them.

I'll have to give this a lot more thought.

My initial reaction is to completely replace the `deployer` with a `build.clj` script (at the top of the workspace) using `tools.build` and change `build.sh` to use that instead of running `build-uberjar.sh` (the rewritten deployer would not use that shell script or `build-thin-jar.sh`).

It looks like only `poly` and `api` get built/deployed so I'm not sure what the `core` project is about (except, perhaps, for testing in a non-dev context?).

**Comment by seancorfield** [comment]
Is the `java` code used anywhere at this point? I can't find any references to the package or classes anywhere (except in that `build-core-api.sh` file which, like `build.sh`, does a `sudo cp` to overwrite existing files (in the local Maven repo, whereas `build.sh` overwrites stuff in `/usr/local`).

**Comment by tengstrand** [comment]
I suggest that you work from the `shell` branch if you haven't already.

The core project isn't used any more and is deleted from the `shell` branch, but I forgot to remove the corresponding script, but it's deleted now. I also downgraded the `jline` library to `3.20.0`. I had a local `3.20.1` which was the reason it worked on my local machine. These changes are now pushed to the `shell` branch.

Yes, `build-api.sh` is an orphan script that I used locally before. I have removed it now from the `shell` branch.

I sounds right to replace the `deployer` component with `tools.build`. 

The `scripts/create-example.sh` uses the `poly` command/script and calls `scripts/output/help/update-command-doc.sh` which in the end generates `doc/commands.md` with the output from the different commands. That's the connection to the `build.sh` script today, that we have to generate the `poly.jar` first, so that we use the latest version.

I have updated the version to `0.2.13-alpha-02`.

**Comment by seancorfield** [comment]
So the `java` folder should also be deleted now on the `shell` branch?

**Comment by tengstrand** [comment]
Yes, let's just delete it. I used it to build a jar that could be used from `Kotlin` (or any other JVM language) by exposing it as compiled Java byte code, instead of normal Clojure AOT compiled code. The idea was to reuse the `workspace` component from Kotlin. I think that was the wrong idea and that if we want to support other languages, it's better to write the code in Clojure.

**Comment by seancorfield** [comment]
Thanks. I'll leave it up to you to delete that `/java` folder and I'll just ignore it for now.

I'll focus on creating a top-level `build.clj` file and `:build` alias to provide parity to the two public functions in the `deployer` component -- but I won't delete the component (or the base) until you're comfortable with the replacement code (since there are no tests for the `deployer` code!).

It'll be kind of interesting having a `:build` alias that ends up depending on so many `components` (since the `deployer` depends on a bunch of stuff), so what I will probably do is have a `projects/build` and a `bases/build` brick since then I can still rely on `poly` to check/test stuff.

**Comment by seancorfield** [comment]
I don't have the `poly` tool installed via `brew` so I guess I need that for testing the updated `build.sh` script (which will in turn just run `clojure -T:build <something>` followed by that `sudo cp ...`

Correction: `brew`'s installation of `poly` does not create that setup -- is it something specific to your local environment?

```bash
> brew info poly
polyfy/polylith/poly: stable 0.2.12-alpha
A tool used to develop Polylith based architectures in Clojure
https://github.com/polyfy/polylith
/usr/local/Cellar/poly/0.2.12-alpha (4 files, 24.5MB) *
  Built from source on 2021-09-14 at 17:52:05
From: https://github.com/polyfy/homebrew-polylith/blob/HEAD/Formula/poly.rb
License: EPL-1.0
> ls -l /usr/local/polylith/poly.jar
ls: /usr/local/polylith/poly.jar: No such file or directory
```

**Comment by seancorfield** [comment]
Building a working JAR from Polylith turns out to be complicated -- `depstar` just happened to "do the right thing" in terms of copying files but I'm not quite sure what it does with (transitive) dependencies. I have that all working with `tools.build` directly now -- with a bit of surgery on the basis and an explicit directory copy of (transitive) source code that works _for the specific case of the `poly` repo_.

The next step is to write the rest of the deployer as a build script -- I plan to have files in `resources` that act as the templates for the homebrew stuff that is currently bashed together as strings in the deployer (using `tools.build`'s `copy-dir` with substitutions). The partial -> full `pom.xml` stuff is already done -- and the dependencies are automatically computed so we will no longer need to keep those updated manually (I suspect that's what you're doing right now, given that Portal was missing for the new `tap` stuff?).

**Comment by tengstrand** [comment]
Yes, the `build.sh` script is something that I've been using locally, which explains why it only works for me. I think it was created even before we had support for `brew`. With that in mind, I hope you can figure out what to do with the new script that replaces it!

Yes, I update dependencies to external libraries manually today.

The way you suggest to implement this sounds good to me. I haven't had time to play around with `tools.build` yet, but I have a general understanding of it at least! I don't know if @furkan3ayraktar has anything to add.

I also want to thank you for helping out with this migration to `tools.build`!

**Comment by seancorfield** [comment]
All I did to `build.sh` was change:

```bash
cd scripts
./build-uberjar.sh poly
```

to:

```bash
clojure -T:build uberjar :project poly
```

(and fixed the `cp` command since it now runs from the directory above)

No more manual `pom.xml` updates are needed!

The JAR building is going to need to be abstracted out to work with general Polylith repos because you can't currently build a library JAR easily with either `depstar` or `tools.build` -- they get the dependencies wrong by default -- so this work will ultimately benefit everyone building library JARs with Polylith.

I'll continue updating this issue as I make progress on this. I expect to continue working on it tomorrow.

**Comment by seancorfield** [comment]
Q for both of you @tengstrand and @furkan3ayraktar : how important is the deployer check that prevents you building or deploying artifacts if there are no changes in the `poly` / `api` projects?

That check alone drags in a huge number of components (because the `api` depends on so many other things transitively) and it feels very much against the spirit of a "build" that should trust the developer. It's a single checkpoint so it's "easy" to add, but it just sort of feels weird that the build ends up relying on so much code that it is actually "building" artifacts for.

**Comment by furkan3ayraktar** [comment]
I think it is a good example for Polylith users to see how they can implement a similar logic for their workspaces. If we remove it, we'll need to provide an example of it in the documentation I suppose. 

However, it doesn't necessarily need to be part of the build script. We can also run another command before the build script and decide if we need the build (e.g. there are affected projects from the latest changes). 

What do you think @tengstrand ?

**Comment by seancorfield** [comment]
Current status:

```bash
(! 847)-> clojure -T:build create-artifacts
Creating artifacts for: poly
Compiling polylith.clj.core.poly-cli.core ...
Building uber jar: target/poly.jar ...
Uberjar is built.
a poly
a poly/install.sh
a poly/poly
a poly/poly-0.2.13-alpha-02.jar
Shasum for poly: c92932736a17cf530539d03fc981605c8feb889e93d3865adc76e380ff30c92e

Thu Oct 07 00:41:39
(sean)-(jobs:0)-(/Developer/workspace/sean-polylith)
(! 848)-> ls -l artifacts/
total 115072
-rw-r--r--  1 sean  staff  31328559 Oct  7 00:41 poly-0.2.13-alpha-02.jar
-rw-r--r--  1 sean  admin  27581372 Oct  7 00:41 poly-0.2.13-alpha-02.tar.gz
-rw-r--r--  1 sean  admin        64 Oct  7 00:41 poly-0.2.13-alpha-02.tar.gz.sha1

Thu Oct 07 00:41:50
(sean)-(jobs:0)-(/Developer/workspace/sean-polylith)
(! 849)-> clojure -M:create-artifacts
Creating artifacts for: poly
Building uberjar...
Uberjar is built.
Shasum for poly: 6e700ab26089226dc70d1f590539d35873515337b16917ffd78bb31334ed9e98

Thu Oct 07 00:42:48
(sean)-(jobs:0)-(/Developer/workspace/sean-polylith)
(! 850)-> ls -l artifacts/
total 117976
-rw-r--r--  1 sean  admin  32121939 Oct  7 00:42 poly-0.2.13-alpha-02.jar
-rw-r--r--  1 sean  admin  28274471 Oct  7 00:42 poly-0.2.13-alpha-02.tar.gz
-rw-r--r--  1 sean  admin        64 Oct  7 00:42 poly-0.2.13-alpha-02.tar.gz.sha1
```

The difference in size for the JAR file seems to be due to different versions of `tools.deps.alpha` being used (I'll double-check that before I'm done).

**Comment by tengstrand** [comment]
I think we can lift out the functionality that calculates whether the build should be executed or not into a separate script @furkan3ayraktar.

**Comment by furkan3ayraktar** [comment]
What do you think about adding a command in poly that can spit out the names of the projects changed? It could be useful for CI jobs, etc. Something like `poly changed-projects`?

**Comment by tengstrand** [comment]
This statement does that: `poly ws get:changes:changed-or-affected-projects skip:dev`

**Comment by tengstrand** [comment]
Also, when we add support for custom commands, people can add that command themselves if they want to!

**Comment by seancorfield** [comment]
The PR is https://github.com/polyfy/polylith/pull/142 for @tengstrand and @furkan3ayraktar to review.

As noted there, I'd probably prefer this just be `build.clj` at the top of the repo but thought it might be easier to grok alongside the `deployer` as a base + project.

Also, as noted there, for this switch to be complete, the `deployer-cli` and `deployer` bricks should go away, along with the `:create-artifacts` and `:deploy` aliases in the workspace `deps.edn` file (and the `java` project can go away too).

**Comment by seancorfield** [comment]
One thing the build script could do is run that `poly ws get:changes:changed-or-affected-projects skip:dev` command, since `tools.build` can construct a `java` command to run Clojure programs, the same way the CLI does. That would be a nice "compromise" between what a "build script" should be doing -- running commands -- vs relying on Polylith's tool code.

And having spent some more time thinking about the `build.clj` vs bricks comment above, I _am_ going to move that code around and have a more traditional `build.clj` in the workspace root and remove the `build` base and project -- ~so expect an updated PR tomorrow. Feel free to review/provide comments/feedback on the PR as it stands if you want and I can incorporate that into the updates...~ I went ahead and made that change already (it was a lot easier than I expected). I'll have a go at the changed project command tomorrow.

**Comment by tengstrand** [comment]
Wow, what a nice piece of work and contribution @seancorfield!
I will have a closer look of it today and hopefully @furkan3ayraktar will also have some time today or tomorrow, so that we can include this in the next release that I plan to do this weekend.

**Comment by seancorfield** [comment]
I just pushed an update with the changed projects check in there as well, by using `java-command` and `process` from `tools.build` to run that `poly` command (from source), so I believe this is complete in terms of parity with the `deployer` stuff -- and you get a few bonus commands since you can directly create the homebrew scripts, the JAR files, and the uberjar separately as `clojure -T:build` tasks.

**Comment by furkan3ayraktar** [comment]
PR #142  is merged into `shell` branch now. It needs a little bit more love from @tengstrand but soon should be ready to be merged into master

**Comment by seancorfield** [comment]
Thank you! Let me know what "more love" it needs, so I can be aware of that for future PRs.

**Comment by seancorfield** [comment]
Looking at the `shell` branch, I see some potential changes to the documentation around build/deploy -- the PR does not touch any of the examples stuff as @tengstrand said that should be done as a separate PR. PR #142 is solely about building Polylith itself, not about how users should set up and build their own projects.

**Comment by tengstrand** [comment]
I will work on the documentation and the `scripts/create-example.sh` script tonight. I can let you know when that is done @seancorfield.

**Comment by tengstrand** [comment]
I will continue with the documentation tomorrow in the `shell` branch.

**Comment by seancorfield** [comment]
~Re: documentation for the `poly` tool moving to GitBook -- presumably, the `polylith` README will shrink down to just a summary and links to the GitBook stuff once you're done?~ I see you just did that, since I last looked! :)

**Comment by tengstrand** [comment]
I'm trying to deploy, but the [CI build](https://app.circleci.com/pipelines/github/polyfy/polylith/503/workflows/b83c75ca-ca12-4bf1-ba98-b316986503f7/jobs/1209) doesn't manage to download the `io.github.seancorfield/build-clj library` library. Do you @seancorfield or maybe @furkan3ayraktar have any ideas?

Solved. Thanks for the help @seancorfield !

**Comment by seancorfield** [comment]
Per Slack, the CI image needs to be updated to a newer Clojure CLI version (>= 1.10.3.933 so it has all the "tools" support).
