### ISSUE TITLE
Parameterized layout names

### ISSUE THREAD

**Issue by vemv** [polyfy/polylith#158]
Hi,

I have a suggestion that would help me adopt and enjoy Polylith more fully. 

## Context

Polylith has specific names for components, bases, bricks, interfaces, projects, workspaces, etc. Naming is hard, and also subjective.

For people coming from different backgrounds, a slightly different set of names can help see things more clearly, making adoption + daily work more comfortable.

As a personal example, prior to Polylith I had used 3 other similar solutions in Clojure (be them bespoke or using a certain framework). The point being, one can get pretty used to a specific set of names/concepts, and letting go of them can feel wasteful.

I also try to avoid using identical names for different, yet vaguely similar ideas. I'm talking about Stuart Sierra `components` vs. Polylith `components`. I'm not sure I see myself having to clarify _Sierra_ component or _Polylith_ component on a daily basis, seems awkward.

Finally, I think that this would easy migration for projects using similar tech. For example if one such project used the word `api` instead of `interface` for N years, then it'd be painful to make all prior documentation, commits, chat logs, etc suddenly invalid.

## Proposal

Parameterize the names that the `poly` tool accepts and handles. Other concerns such as the layout itself wouldn't be affected.

This would mean essentially un-hardcoding strings, and moving them to a centralized, customizable definition:

```clj
(def component-name
  "The name for 'components' that a given workspace has chosen to use, in singular."
  (System/getProperty "polylith.component-name"
                      ;; the default:
                      "component"))

(def components-name
  "The name for 'components' that a given workspace has chosen to use, in plural."
  (System/getProperty "polylith.components-name"
                      (str component-name "s")))
```

This seems a fairly cheap and non-breaking thing to do. I could do the work (one name at a time, for getting good at it).

Let me know what you think.

Cheers - V

**Comment by tengstrand** [comment]
Hi @vemv,

We have discussed this within the core team, and though we understand the thrust of your argument, 
we don’t believe that making this change would be good for Polylith in the long-term.

We see great value in the fact that all Polylith projects use the same nomenclature of the core concepts: 
interface, component, base, brick, project, and workspace.

This help people switch between different Polylith codebases because they will look the same. Your code will be in sync with the vocabularies used in the documentation. It will be easier when you communicate with other Polylith users when you speak the same language, and it will help you understand the output from different commands where these concepts are used.

Regards,
The Polylith Team
