### ISSUE TITLE
Support aliases in paths

### ISSUE THREAD

**Issue by tengstrand** [polyfy/polylith#230]
See [aliases](https://clojure.org/reference/deps_and_cli#_paths).

**Comment by seancorfield** [comment]
While this may not be a very necessary feature for Polylith since `:paths` and `:extra-paths` aren't likely to be anything unusual, this is something supported by core `tools.deps.alpha` code, and Polylith should not prevent it from being used/working.

Right now, if you try to use aliases in paths -- per Clojure CLI documentation -- Polylith throws an exception:

```
#error {
 :cause {:paths [["should be a string"]]}
 :via
 [{:type java.lang.Exception
   :message {:paths [["should be a string"]]}
   :at [polylith.clj.core.workspace_clj.config_from_disk$read_config_file invokeStatic config_from_disk.clj 24]}]
 :trace
 [[polylith.clj.core.workspace_clj.config_from_disk$read_config_file invokeStatic config_from_disk.clj 24]
  [polylith.clj.core.workspace_clj.config_from_disk$read_config_file invoke config_from_disk.clj 14]
  [polylith.clj.core.workspace_clj.components_from_disk$read_component invokeStatic components_from_disk.clj 20]
  [polylith.clj.core.workspace_clj.components_from_disk$read_component invoke components_from_disk.clj 11]
  [polylith.clj.core.workspace_clj.components_from_disk$read_components$fn__30240 invoke components_from_disk.clj 34]
```

Both `calc-basis` and `make-classpath-map` do the unrolling of aliases in paths automatically.

**Comment by tengstrand** [comment]
I didn't manage to solve the problem with `calc-basis` so I simple substituted the paths myself (it's not much code). Please have a look @seancorfield.

**Comment by seancorfield** [comment]
I'm not sure what are all the possible combinations in `tools.deps.alpha` but that PR looks like it covers the basics so it'll be good enough for now. I didn't realize you weren't using t.d.a for handling everything in the `deps.edn` file.
