### ISSUE TITLE
Print total number of tests run with poly test when all tests pass

### ISSUE THREAD

**Issue by bpringe** [polyfy/polylith#240]
**Is your feature request related to a problem? Please describe.**

For each brick tested when I run `poly test` I see output such as "Test results: 1 passes, 0 failures, 0 errors." However, I can't see the total number of tests that passed, failed, or errored.

**Describe the solution you'd like**

I'd like this output at the end of all tests being run for all bricks, reporting the totals (how many tests passed in total, etc.).

**Comment by ieugen** [comment]
Hi, if you need more than just the total tests, there is kaocha via https://github.com/imrekoszo/polylith-kaocha 

I use junit xml reports for which there are tools to display.
Kaocha also has better reporting from my limitted experience.

**Comment by bpringe** [comment]
Thanks for the suggestion.

**Comment by tengstrand** [comment]
Hi @bpringe,

Since we started to support external test runners, the [test-runner-orchestrator](https://github.com/polyfy/polylith/tree/master/components/test-runner-orchestrator) doesn't know which test runner that is used when executing the tests, and we have no specified contract to the test runner at the moment, so we don't know how many tests were executed.

I consider it to be too much work at the moment to add support for this, so I will close this issue and recommend you to use the Kaocha test runner instead (as @ieugen  pointed out) if the total number of executed tests is important for you.
