### ISSUE TITLE
Usage/clarification on extra-paths for issue-66

### ISSUE THREAD

**Issue by gnarroway** [polyfy/polylith#78]
Hi,

I am trying out the issue-66 branch (each component has a deps.edn) and have some questions. 

1. In `projects/foo/deps.edn`, I get an error 107 if I do not specify all the components explicitly, even if they are all implicitly included via the base project it depends on. What is the purpose of this? Is it so the poly tool can more easily figure out the dependency table?
2. In the root `deps.edn`, what is the purpose of specifying `:extra-paths` in the dev alias? The repl etc seem to work with just the `:extra-deps` so I am wondering if this is an artifact of the poly design prior to #66. That said, cursive seems to use the paths to mark “source directories”, but other IDEs don’t seem to do much with it. 

Ultimately our goal is to remove boilerplate while still getting the benefits of the design and tooling, so am wondering if these parts can be omitted safely. 

Thanks!

**Comment by tengstrand** [comment]
Hi!

Sorry for late answer. I've been busy, so totally missed looking here!

1. I'm rewriting the way the dependencies are calculated in the `issue-66` branch right now. This is work in progress, and I haven't pushed anything yet, but the goal is to fix issues with the way dependencies are calculated today, including some corner cases, support for `test` dependencies and to be more fine granular by following imported namespaces individually when calculating dependencies. Components and bases only depend on `interfaces` and they don't know about concrete components. This is the reason you have to specify all the concrete components and bases that are included in a project.
2. The `issue-66` branch already supports both `:extra-paths` and `:extra-reps` as you recognised. I will soon update the documentation to reflect that. The use of `extra-deps` should be the preferred way to configure `./deps.edn` as long as you don't have any problems with your IDE (I will reach out to Colin "Cursive" Fleming soon to see if the problem you mentioned can be addressed). 

The `issue-66` branch was not meant to be used in production, because it is work in progress and a few breaking changes will be introduced and announced at the top of the documentation when that happens. This will include a change to how `tag-patterns` will be configured in `workspace.edn`. Some badly named attributes in the internal workspace structure will also be changed. That should be a minor problem, because it will only affect you if you exported the workspace to a file with the `ws` command and then try to execute a command using the `ws-file:FILE` argument with a later version of the `poly` tool.

Because people have started to use the `issue-66` branch in production (which is kind of cool) I now need to be very careful about what I push there and I will do my best to not beak anything!

**Comment by tengstrand** [comment]
I added issue [2554](https://github.com/cursive-ide/cursive/issues/2554) to Cursive.

**Comment by tengstrand** [comment]
This should now work in `master`.
