### ISSUE TITLE
Interfaces as unnecessary indirection and boilerplate

### ISSUE THREAD

**Issue by kendagriff** [polyfy/polylith#96]
**Is your feature request related to a problem? Please describe.**
When writing a component, the docs recommend the creation of a core.clj and interface.clj. What value is this adding, and does that value exceed the cost of additional indirection and boilerplate? For example, if you place docstrings on your core functions (where it belongs), you have to duplicate it in your interface for it to be useful to other components. What purpose does this serve?

**Describe the solution you'd like**
I get that I can use core.clj without an interface file, but am I missing anything?

Thanks for Polylith, by the way! Loving it!

**Comment by tengstrand** [comment]
Hi!

If I understand your question right, you are asking why we don't put all our code in the interface namespace.

The answer is that it often makes the code easier to read and maintain, and that is also the reason we create both an `interface.clj` and an implementing `core.clj` namespace when creating a brick, because in most cases we also want one or several implementing namespaces (the `core` namespace can be renamed if you prefer another name or deleted if not used). There are exceptions, e.g. the [version](https://github.com/polyfy/polylith/tree/master/components/version/src/polylith/clj/core/version) component in the Polylith codebase, where delegation wouldn't make sense.

A brick (component or base) can only access other interfaces, not namespaces that belong to a concrete component. If you execute the `deps` command, you will notice that all the headings are yellow (interfaces), and that is because bricks can only access other interfaces, not concrete components. This is how Polylith encapsulates functionality and allows us to replace a component with another component if they implement the same interface.

I hope that answered your question and nice that you love Polylith!

**Comment by kendagriff** [comment]
Thanks for the detailed explanation!

Perhaps I'm merely voicing a gripe of mine, that it's not easier to finish a public function, and call it a day; instead, it must be copied to an interface, documentation included, and now the two functions must be permanently maintained together. (Which will be forgotten at times.)

**Comment by tengstrand** [comment]
Yes, I haven't been consistent with that either, where to put the documentation for each function (only the interface, only the implementation, or both). One idea is to have a brief explanation in the interface and a more detailed in the implementation. But if you have a good name for the function and the parameters, then that is sometimes enough for the interface and then we can put a description for the implementation. There are always these trade-offs! Duplicating the same description doesn't sound like the best alternative though.
